print("Введите этапы развития человека (6 этапов):")
print("1 этап:")
a1 = input()
print("2 этап:")
a2 = input()
print("3 этап:")
a3 = input()
print("4 этап:")
a4 = input()
print("5 этап:")
a5 = input()
print("6 этап:")
a6 = input()
print("Ответ:")
print(a1, a2, a3, a4, a5, a6, sep='=> ')
print("правильный ответ: Pliopithecus=> Australopithecus=> Homo habillis=> Homo erectus=> Homo neanderthalensis=> Homo sapiens sapiens")